### PR TITLE
Basic list view for API 10 and below

### PR DESCRIPTION
**Pull request by benhylau**
Make library work for API 11 and above and provide basic list functionality on 10 and below instead of crashing. Also updated to latest libraries.

I want my app to run on Gingerbread even if it means the swipe feature wouldn't work. This should not affect functionality for API 11 and above, but it does pull in the compat libraries and increase library size and method count, so I can understand if you don't accept this PR. In that case please just close the PR. Thanks.

### CODE REVIEW

**Comment by brnunes** [comment]
Hey, thanks for the pull request.
I'm trying to push a new version of the lib to maven, but I'm getting some dependency problems when generating the javadoc. If you are good with Gradle you might be able to help me.
[This is the build.gradle](http://pastebin.com/p5eABHKi) for the lib. When I run uploadArchives, I get [this error](http://pastebin.com/FCxiWRkK). So the android.support.v7.widget is not being imported. It seems to be the same problem as [this stackoverflow question](http://stackoverflow.com/questions/34522903/how-to-compile-another-library-into-library).
Previously I was having a few more errors, regarding the `NonNull` annotation, and [this answer](http://stackoverflow.com/questions/29663918/android-gradle-javadoc-annotation-does-not-exists) helped me fix that. However using the same approach for the support-v7 hasn't helped (line 33 of the build.gradle).
Let me know if you have some suggestions for me to try.

**Comment by benhylau** [comment]
@brnunes #13 Try this. I didn't test it here, but have done those before.

Also let me know about this PR. I am kinda 50/50 because it pulls in `com.android.support:support-v4`, which adds like 8k to the DEX count. What do you think?

**Comment by benhylau** [comment]
@brnunes Hey did you get a chance to try out the deploy script?

**Comment by brnunes** [comment]
@benhylau I'll do it in the next few days.
About this PR, I'm not sure how to measure the pros and cons. I haven't done much Android development lately, but I imagine only large apps have a problem with DEX count, and if the app is large chances are it already includes the `support-v4` lib (?).
Maybe releasing two versions of the lib is a solution?

**Comment by benhylau** [comment]
Yea you are right, it mostly affects large apps that integrate lots of third party libraries, and chances are somehow `support-v4` already got pulled in from some of those. Releasing two versions I think is the best solution, but may be too much trouble to maintain two branches just because of this.

**Comment by brnunes** [comment]
@benhylau I've published a new version to maven, it should be online now. Please give it a try to see if everything is well.

**Comment by benhylau** [comment]
Thanks I should try it soon.

**Comment by benhylau** [comment]
I will post results here: https://github.com/hyperboria/android/issues/56

**Pull request merged**
